name: Security Scan 🛡️

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly as a safety net

  
jobs:
  security-scan:
    name:  Security Scan 🛡️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: always()
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: foobar
        if: always()
      - name: Run Semgrep (Code Logic / SAST) 🧠
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default # Uses the smartest community-driven rulesets
        if: always()
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'           # Scans the file system/repo
          ignore-unfixed: true      # Ignores vulns without a known fix yet
          format: 'table'           # Clean output in the GitHub Actions logs
          exit-code: '1'            # Fails the action if vulns are found
          severity: 'CRITICAL,HIGH' # Only blocks on major issues
        if: always()
